/**
 * Generates every output from tokens.json — the single source of truth.
 *
 * Never hand-edit anything in dist/. If a value is wrong, it is wrong in
 * tokens.json and both apps are wrong together, which is the point.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, '..', 'dist')
const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'))

const BANNER = `/* GENERATED by packages/tokens/src/build.mjs — do not edit.
   Source of truth: packages/tokens/src/tokens.json */\n`

/** Groups whose values are per-theme objects rather than plain strings. */
const THEMED = new Set(['color', 'shadow'])

/** Every token group that becomes a CSS custom property, in output order. */
const GROUPS = ['color', 'radius', 'shadow', 'fontSize', 'space', 'motion', 'size', 'font']

const isThemed = (group, value) =>
  THEMED.has(group) && value !== null && typeof value === 'object'

/** Resolve one token for one theme. Falls back to `light` so a token that is
 *  genuinely theme-independent (e.g. --star) needs no dark entry. */
function resolve(group, value, theme) {
  if (!isThemed(group, value)) return value
  return value[theme] ?? value.light
}

function cssBlock(selector, theme, { themedOnly = false } = {}) {
  const lines = []
  for (const group of GROUPS) {
    const entries = Object.entries(tokens[group] ?? {})
    const emitted = []
    for (const [name, value] of entries) {
      if (themedOnly && !isThemed(group, value)) continue
      // A themed token with no distinct dark value would be a no-op override.
      if (themedOnly && resolve(group, value, theme) === resolve(group, value, 'light')) continue
      const comment = isThemed(group, value) && value.comment && theme === 'light'
        ? `  /* ${value.comment} */\n`
        : ''
      emitted.push(`${comment}  --${name}: ${resolve(group, value, theme)};`)
    }
    if (emitted.length) lines.push(emitted.join('\n'))
  }
  if (!themedOnly) {
    const aliases = Object.entries(tokens.alias ?? {}).map(([k, v]) => `  --${k}: ${v};`)
    if (aliases.length) lines.push(aliases.join('\n'))
  }
  return `${selector} {\n${lines.join('\n\n')}\n}\n`
}

// ---- tokens.css -----------------------------------------------------------
// Light on bare :root, dark under the attribute only. Matches the sibling's
// strategy deliberately: the dark values live in exactly ONE rule so the two
// copies cannot drift, and the attribute (not the media query alone) means a
// person who wants dark at noon can have it.
const css = [
  BANNER,
  cssBlock(':root', 'light'),
  '\n',
  `:root[data-theme='dark'] {\n${cssBlock(':root', 'dark', { themedOnly: true })
    .split('\n')
    .slice(1, -2)
    .join('\n')}\n}\n`,
].join('')

// ---- tokens.ts ------------------------------------------------------------
const flat = {}
for (const group of GROUPS) {
  for (const [name, value] of Object.entries(tokens[group] ?? {})) {
    flat[name] = isThemed(group, value)
      ? { light: resolve(group, value, 'light'), dark: resolve(group, value, 'dark') }
      : value
  }
}

const tokenNames = Object.keys(flat)
const ts = `${BANNER}
export type TokenName = ${tokenNames.map((n) => `'${n}'`).join(' | ')}

export type Theme = 'light' | 'dark'

/** Raw token values. Themed tokens carry both variants. */
export const tokens = ${JSON.stringify(flat, null, 2)} as const

/** \`var(--name)\` for a token, type-checked. Prefer this over string literals. */
export const cssVar = (name: TokenName): string => \`var(--\${name})\`

/** The resolved value for a theme. Use only where CSS variables cannot reach
 *  (canvas, native bridges, meta theme-color). In CSS, always use cssVar. */
export function tokenValue(name: TokenName, theme: Theme = 'light'): string {
  const v = tokens[name] as string | { light: string; dark: string }
  return typeof v === 'string' ? v : v[theme]
}
`

mkdirSync(dist, { recursive: true })
writeFileSync(join(dist, 'tokens.css'), css)
writeFileSync(join(dist, 'tokens.ts'), ts)

console.log(
  `tokens: ${tokenNames.length} tokens -> dist/tokens.css, dist/tokens.ts`,
)
