/**
 * Device database encryption — the contract, before the driver exists.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS FILE EXISTS NOW, WITH NO SQLCIPHER IN IT
 *
 * The readiness ledger carries "no device DB encryption" as days of work, as
 * though SQLCipher were a flag to add to an existing driver. It is not, because
 * THERE IS NO DEVICE DRIVER YET. Capacitor is anticipated in comments and in
 * the Vite config, but it is not installed; the only implementation of
 * SqlDriver is the node:sqlite one used by tests.
 *
 * That makes the ordering the actual risk. Whoever builds the Capacitor driver
 * will build it the short way first — open a database, get sync working, come
 * back for encryption — and two things go wrong the moment they do:
 *
 *   1. There is a shipped build in between with the whole fleet, purchase
 *      prices, replacement values and the customer list in plaintext on a
 *      Redmi in a tech's pocket.
 *   2. SQLCipher CANNOT OPEN A PLAINTEXT DATABASE. Retrofitting means every
 *      installed device needs an export/re-import migration, executed offline,
 *      on phones that may not check in for days. The device-only tables — the
 *      outbox above all — exist nowhere else, so a migration that goes wrong
 *      destroys unsent scans with no server-side copy to fall back on.
 *
 * So the requirement is encoded as a TYPE and a TEST rather than a note in a
 * document. A device driver cannot be constructed without a key provider,
 * because `openDeviceDatabase` will not accept one, and the test asserts the
 * test driver is refused for device use. It is not possible to reach "working
 * but unencrypted" by accident.
 *
 * This is a seam and a guard, not encryption. It is honest about that. What it
 * buys is that the encryption, when written, cannot be skipped or deferred.
 * ---------------------------------------------------------------------------
 */

import type { SqlDriver } from './driver.ts'

/**
 * Where the key comes from.
 *
 * On Android: a 256-bit key generated by and held in the **Android Keystore**,
 * which keeps it in hardware-backed storage the app can use but cannot read.
 * That is the property that matters — a key in shared preferences, or derived
 * from something guessable like the device id, is decoration. An attacker with
 * the phone has the app's own storage.
 *
 * NOT derived from the user's PIN. A PIN is four to six digits and is
 * brute-forceable offline in seconds once the file is copied off the device;
 * binding the database to it would make the encryption theatre. The PIN gates
 * the SESSION; the Keystore holds the KEY. They protect different things.
 */
export interface DeviceKeyProvider {
  /**
   * The passphrase for SQLCipher's `PRAGMA key`.
   *
   * Async because a hardware-backed keystore call is, and because forcing the
   * async shape now avoids reworking every call site later.
   */
  getKey(): Promise<string>

  /**
   * Destroy the key, making the database permanently unreadable.
   *
   * This is the wipe. It is a key deletion rather than a file deletion because
   * deleting a file on Android is not a guarantee of anything, while a
   * ciphertext whose key is gone is genuinely unrecoverable.
   *
   * ⚠ THE OUTBOX DIES WITH IT. Unsent scans exist nowhere else — not on the
   * server, not anywhere. The readiness ledger already names this as a limit
   * that cannot be engineered away. A wipe must therefore be a deliberate act
   * with a flush attempted first, never an automatic response to a transient
   * condition such as "the session looks stale".
   */
  wipe(): Promise<void>
}

/**
 * What a driver must declare about itself.
 *
 * `ephemeral` is the honest description of the node:sqlite and in-memory
 * drivers: their contents do not survive the process, so there is nothing at
 * rest to protect. `encrypted` means SQLCipher with a key from a
 * DeviceKeyProvider. `plaintext` exists ONLY so that a driver can name itself
 * accurately and be refused — there is no way to construct a device database
 * with it.
 */
export type StorageProtection = 'encrypted' | 'ephemeral' | 'plaintext'

export interface DeviceDriverFactory {
  readonly protection: StorageProtection
  /** Human-readable, for the error message when this is refused. */
  readonly name: string
  open(key: string): SqlDriver
}

export class UnencryptedDeviceDatabaseError extends Error {
  constructor(driverName: string, protection: StorageProtection) {
    super(
      `Refusing to open a device database with the "${driverName}" driver ` +
        `(protection: ${protection}). A device database must be SQLCipher-encrypted ` +
        `with a key from the Android Keystore — see packages/core/src/db/device-key.ts. ` +
        `If this is a test, use an ephemeral driver and openEphemeralDatabase().`,
    )
    this.name = 'UnencryptedDeviceDatabaseError'
  }
}

/**
 * The only supported way to open the database on a real device.
 *
 * Requires a key provider by signature, so "I'll add encryption after sync
 * works" is not reachable — there is no overload that omits it.
 */
export async function openDeviceDatabase(
  factory: DeviceDriverFactory,
  keys: DeviceKeyProvider,
): Promise<SqlDriver> {
  if (factory.protection !== 'encrypted') {
    throw new UnencryptedDeviceDatabaseError(factory.name, factory.protection)
  }

  const key = await keys.getKey()

  // An empty key is not an error in SQLCipher — it opens the database
  // UNENCRYPTED, silently. That is the single most dangerous failure mode in
  // this file, because everything downstream works perfectly and the data is
  // in plaintext. Checked here rather than trusted to the provider.
  if (key.length === 0) {
    throw new UnencryptedDeviceDatabaseError(factory.name, 'plaintext')
  }

  return factory.open(key)
}

/**
 * For tests and the desk console's throwaway state.
 *
 * Separate function rather than a flag on the one above: a boolean parameter
 * named something like `allowUnencrypted` is a thing people pass `true` to at
 * 2am. A differently-named function is not reached by accident.
 */
export function openEphemeralDatabase(factory: DeviceDriverFactory): SqlDriver {
  if (factory.protection === 'plaintext') {
    throw new UnencryptedDeviceDatabaseError(factory.name, 'plaintext')
  }
  return factory.open('')
}
